version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root1234!!
      MYSQL_DATABASE: payment
    ports:
      - "3306:3306"

  api:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/payment?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234!!
    depends_on:
      - db
    ports:
      - "8080:8080"