server:
  port: 8443
  ssl:
    key-store: classpath:keystore-prod.p12
    key-store-password: password1!
    key-password: password1!
    key-alias: tomcat

spring:
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://proejct-rds-mysql8.cjug24qm0gxh.ap-northeast-2.rds.amazonaws.com:3306/sideproject
    username: developer
    password: password1!

logging:
  level:
    root: WARN

toss:
  payments:
    base-url: "https://api.tosspayments.com"
    secret-key: "test_sk_EP59LybZ8BploGpKdzqJV6GYo7pR"
    authorization-type: "Basic"
    content-type: "application/json"