spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234!!

logging:
  level:
    root: INFO

server:
  port: 8443
  ssl:
    key-store: classpath:keystore-local.p12
    key-store-password: password1!
    key-store-type: PKCS12
    key-alias: myalias