name: fintech-service CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build all modules
        run: ./gradlew clean build

      - name: Run tests
        run: ./gradlew test

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Deploy to production server
        run: |
          echo "Deploying to production server..."
          scp ./api/build/libs/*.jar user@your-server:/path/to/api/
          scp ./db/build/libs/*.jar user@your-server:/path/to/db/
          ssh user@your-server "cd /path/to/api/ && java -jar api.jar"
          ssh user@your-server "cd /path/to/db/ && java -jar db.jar"